### PR TITLE
Profile support

### PR DESCRIPTION
**Pull request by dannymandel**
Initial support for [profiles](https://github.com/isamplesorg/isamples_inabox/issues/187)

Still need to run the automated tests against this, but initial support seems to be working

### CODE REVIEW

**Comment by dannymandel** [comment]
New resolve request

```
(isb) mandeld@SBS-7448 isamples_inabox % curl -v "http://localhost:8000/resolve/IGSN:NHB002HCG"                              
*   Trying 127.0.0.1:8000...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /resolve/IGSN:NHB002HCG HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< date: Thu, 21 Jul 2022 01:34:34 GMT
< server: uvicorn
< location: http://localhost:8000/thing/IGSN:NHB002HCG
< transfer-encoding: chunked
< 
* Connection #0 to host localhost left intact
```

**Comment by dannymandel** [comment]
Get resource by profile with header

```
(isb) mandelds-MacBook-Pro:isamples_inabox mandeld$ curl --header "Accept-Profile: <https://w3id.org/isample/schema>"  -v "http://localhost:8000/thing/IGSN%3AODP02Q188"
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /thing/IGSN%3AODP02Q188 HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.64.1
> Accept: */*
> Accept-Profile: <https://w3id.org/isample/schema>
> 
< HTTP/1.1 200 OK
< date: Wed, 20 Jul 2022 18:47:00 GMT
< server: uvicorn
< content-profile: https://w3id.org/isample/schema
< content-length: 1145
< content-type: application/ld+json
```

**Comment by dannymandel** [comment]
List profiles request with head

```
(isb) mandeld@SBS-7448 isamples_inabox % curl -I -v "http://localhost:8000/thing/IGSN:NHB002HCG"
*   Trying 127.0.0.1:8000...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> HEAD /thing/IGSN:NHB002HCG HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< date: Thu, 21 Jul 2022 01:01:24 GMT
date: Thu, 21 Jul 2022 01:01:24 GMT
< server: uvicorn
server: uvicorn
< content-profile: <http://www.w3.org/ns/dx/conneg/profile/qsa>
content-profile: <http://www.w3.org/ns/dx/conneg/profile/qsa>
< link: <http://localhost:8000/thing/IGSN:NHB002HCG?_profile=isamples>; rel="canonical"; type="application/json"; profile="https://w3id.org/isample/schema", <http://localhost:8000/thing/IGSN:NHB002HCG?_profile=source>; rel="alternate"; type="application/json"; profile="https://w3id.org/isample/source_record"
link: <http://localhost:8000/thing/IGSN:NHB002HCG?_profile=isamples>; rel="canonical"; type="application/json"; profile="https://w3id.org/isample/schema", <http://localhost:8000/thing/IGSN:NHB002HCG?_profile=source>; rel="alternate"; type="application/json"; profile="https://w3id.org/isample/source_record"
< content-length: 2
content-length: 2
< content-type: application/json
content-type: application/json
```

**Comment by dannymandel** [comment]
List profiles request with qsa

```
(isb) mandeld@SBS-7448 isamples_inabox % curl -v "http://localhost:8000/thing/IGSN:NHB002HCG?_profile=all"
*   Trying 127.0.0.1:8000...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /thing/IGSN:NHB002HCG?_profile=all HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< date: Wed, 20 Jul 2022 22:59:15 GMT
< server: uvicorn
< content-profile: <http://www.w3.org/ns/dx/conneg/profile/qsa>
< link: <http://localhost:8000/thing/IGSN:NHB002HCG?_profile=isamples>; rel="canonical"; type="application/json"; profile="https://w3id.org/isample/schema, <http://localhost:8000/thing/IGSN:NHB002HCG?_profile=source>; rel="alternate"; type="application/json"; profile="https://w3id.org/isample/source_record
< content-length: 2
< content-type: application/json
< 
* Connection #0 to host localhost left intact
{}%     
```

**Comment by dannymandel** [comment]
Get resource by profile with qsa
```
(isb) mandelds-MacBook-Pro:isamples_inabox mandeld$ curl -v "http://localhost:8000/thing/IGSN%3AODP02Q188?full=false&format=original&_profile=source"
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /thing/IGSN%3AODP02Q188?full=false&format=original&_profile=source HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< date: Wed, 20 Jul 2022 18:38:19 GMT
< server: uvicorn
< content-profile: https://w3id.org/isample/source_record
< content-length: 6197
< content-type: application/ld+json
< 
```

**Review by datadavev — APPROVED** [review]
This all looks good. There's a bit of cleanup we need to do around get_thing, but that's more of a big picture API adjustment based on what we have from UI and synchronization requirements.

**Pull request merged**
